version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - '/app/node_modules'
        depends_on:
            - mysql_server
    mysql_server:
        image: mysql:8.0
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USERNAME}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}

volumes:
    db-data: {}